### ISSUE TITLE
Convenience Sikuli client factory method

### ISSUE THREAD

**Issue by buzdin** [sterodium/selenium-grid-extensions#29]
The following code is too complex

```
String sessionId = remoteWebDriver.getSessionId();
SikuliExtensionClient client = new SikuliExtensionClient(host, port, sessionId);
```

Create factory method, which builds Sikuli client on RemoteWebDriver object instance without the need to pass any other parameters.

**Comment by echoAlexey** [comment]
This will require to bring dependency on selenium-server in sikuli client only for passing Driver to constructor. I suggest to leave constructor as it is.

**Comment by volkovs** [comment]
@echoAlexey I agree it looks like extra step from user's point of view. Also looks like not a big issue, since client already has dependency on selenium-server (it creates `RemoteWebDriver` in the first place). If you don't want to make this dependency propagated we can set the scope to provided. What do you think?

**Comment by echoAlexey** [comment]
Agree, will include in next release. Will look into __optional__ scope for it.
